services:
  nginx:
    ports:
      - "8080:80"
  web:
    env_file:
      - ./config/prod.env
      - ./config/my.env
  celery_flower:
    image: wger/server:latest
    container_name: wger_celery_flower
    command: /start-flower
    env_file:
      - ./config/prod.env
    ports:
      - "5555:5555"
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:5555/healthcheck
      interval: 10s
      timeout: 5s
      retries: 5
    depends_on:
      celery_worker:
        condition: service_healthy
